// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/components/icons/Arrow.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    copy: typeof import('./src/components/game/FormScreen copy.vue')['default']
    FormScreen: typeof import('./src/components/game/FormScreen.vue')['default']
    InstructionIconBlock: typeof import('./src/components/game/instructions/InstructionIconBlock.vue')['default']
    InstructionsScreen: typeof import('./src/components/game/InstructionsScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartScreen: typeof import('./src/components/game/StartScreen.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TruckGame: typeof import('./src/components/game/TruckGame.vue')['default']
  }
}
